name: badminton
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.6.1
  - blas=2.116
  - blas-devel=3.9.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.6.68
  - cuda-runtime=12.1.0
  - cuda-version=12.6
  - expat=2.6.3
  - ffmpeg=4.4.2
  - filelock=3.16.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.7.9
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - jinja2=3.1.4
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.11.1.6
  - libcurand=10.3.7.68
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.21
  - libdrm=2.4.123
  - libegl=1.7.0
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgl=1.7.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.1.0
  - libhwloc=2.11.1
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpciaccess=0.18
  - libpng=1.6.44
  - libsqlite=3.46.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libtasn1=4.19.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libuv=1.49.0
  - libva=2.22.0
  - libvpx=1.13.1
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - markupsafe=2.1.5
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nettle=3.9.1
  - networkx=3.3
  - nodejs=20.17.0
  - openh264=2.3.1
  - openjpeg=2.5.2
  - openssl=3.3.2
  - p11-kit=0.24.1
  - pillow=10.4.0
  - pip=24.2
  - pnpm=9.11.0
  - pthread-stubs=0.4
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.10.12
  - python_abi=3.10
  - pytorch=2.4.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=73.0.1
  - sqlite=3.46.0
  - svt-av1=1.4.1
  - sympy=1.13.3
  - tbb=2021.13.0
  - tk=8.6.13
  - torchaudio=2.4.1
  - torchtriton=3.0.0
  - torchvision=0.19.1
  - typing_extensions=4.12.2
  - urllib3=2.2.3
  - wayland=1.23.1
  - wayland-protocols=1.37
  - wheel=0.44.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.0
  - xorg-xorgproto=2024.1
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - annotated-types==0.7.0
      - anyio==4.6.0
      - astunparse==1.6.3
      - click==8.1.7
      - conda-merge==0.2.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - dnspython==2.6.1
      - dtaidistance==2.3.12
      - email-validator==2.2.0
      - exceptiongroup==1.2.2
      - fastapi==0.115.0
      - fastapi-cli==0.0.5
      - fire==0.6.0
      - flatbuffers==24.3.25
      - fonttools==4.54.1
      - fsspec==2024.9.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.66.1
      - h11==0.14.0
      - h5py==3.12.1
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.2
      - joblib==1.4.2
      - keras==3.5.0
      - keras-embed-sim==0.10.0
      - keras-layer-normalization==0.16.0
      - keras-multi-head==0.29.0
      - keras-pos-embd==0.13.0
      - keras-position-wise-feed-forward==0.8.0
      - keras-self-attention==0.51.0
      - kiwisolver==1.4.7
      - libclang==18.1.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - namex==0.0.8
      - numpy==1.26.4
      - opt-einsum==3.4.0
      - optree==0.12.1
      - packaging==24.1
      - pandas==2.2.3
      - protobuf==4.25.5
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pygments==2.18.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.10
      - pytz==2024.2
      - rich==13.8.1
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - shellingham==1.5.4
      - six==1.16.0
      - sniffio==1.3.1
      - starlette==0.38.6
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.17.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - torchsde==0.2.6
      - tqdm==4.66.5
      - trampoline==0.1.2
      - typer==0.12.5
      - tzdata==2024.2
      - uvicorn==0.31.0
      - uvloop==0.20.0
      - watchfiles==0.24.0
      - websockets==13.1
      - werkzeug==3.0.4
      - wrapt==1.16.0
